global using Microsoft.EntityFrameworkCore;
global using Web.Entites.Models;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using Web.DataAccess.Data;
global using Web.Entites.IRepositories;
global using Web.Entites.ViewModels;
global using Web.DataAccess.Utilities;