global using Microsoft.EntityFrameworkCore;
global using Web.Entites.Models;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using Web.DataAccess.Data;
global using Web.Entites.IRepositories;
global using Web.Entites.ViewModels;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using FluentValidation;
global using Mapster;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.WebUtilities;
global using Microsoft.Extensions.Logging;
global using OneOf;
global using System.Security.Claims;
global using System.Text;
global using Web.Entites.Consts;
global using Web.Entites.ViewModels.UsersVMs;
global using Microsoft.Extensions.Caching.Hybrid;
global using Web.Entites.ViewModels.CartItemVMs;
global using Web.Entites.ViewModels.CartVMs;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using Web.Entites.ViewModels.CategoryVMs;
global using MailKit.Net.Smtp;
global using Microsoft.Extensions.Options;
global using MimeKit;
global using Web.Entites.ViewModels.OrderVMs;
global using Stripe;
global using Stripe.Checkout;
global using Web.Entites.ViewModels.ProductVMs;
global using System.IO;
global using Web.Entites.ViewModels.WishlistVMs;
global using Product = Web.Entites.Models.Product;
global using File = System.IO.File;

